name: 'My WiNet Extractor'
description: 'Copy of original WiNet Extractor which extracts data from WiNet devices and sends to Home Assistant over MQTT.'
version: '0.2.2'
stage: 'stable'
slug: 'my-winet-extractor'
url: 'https://github.com/NickStallman/home-assistant-repo/tree/main/winet-extractor'
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
map:
  - config:rw
panel_icon: mdi:solar-power
auth_api: false
hassio_role: 'default'
hassio_api: false
homeassistant_api: false
startup: 'application'
init: false
services:
  - mqtt:need

options:
  winet_host: '192.168.86.X'
  mqtt_url: 'mqtt://sungrow_mqtt:sungrow_mqtt@core-mosquitto:1883'
  winet_user: ''
  winet_pass: ''
  poll_interval: 10
  analytics: false
  ssl: false

schema:
  winet_host: str
  mqtt_url: str
  winet_user: str?
  winet_pass: str?
  poll_interval: int(1,3600)
  analytics: bool
  ssl: bool
